# Alerting and a single-pane dashboard. Every alarm watches the ALB
# target group or the RDS instance, never the ASG: CodeDeploy replaces
# the ASG on every blue/green deploy (codedeploy.tf), so an alarm keyed
# on an ASG name would silently go stale after the first release. The
# target group and the DB instance are the two identities that survive
# every deploy.

# --- Notification channel ---------------------------------------------

# Customer-managed key, not alias/aws/sns: CloudWatch alarms can't
# publish to a topic encrypted with the AWS-managed SNS key, because
# that key's policy can't be edited to let cloudwatch.amazonaws.com use it.
resource "aws_kms_key" "alerts" {
  description             = "SNS alert topic encryption - appointments"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AccountAdmin"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" }
        Action    = "kms:*"
        Resource  = "*"
      },
      {
        Sid       = "CloudWatchAlarmsPublish"
        Effect    = "Allow"
        Principal = { Service = "cloudwatch.amazonaws.com" }
        Action    = ["kms:Decrypt", "kms:GenerateDataKey*"]
        Resource  = "*"
      },
    ]
  })
}

resource "aws_sns_topic" "alerts" {
  name              = "appointments-alerts"
  kms_master_key_id = aws_kms_key.alerts.id
}

# AWS emails a confirmation link to this address after apply; nothing
# is delivered until it's clicked.
resource "aws_sns_topic_subscription" "alerts_email" {
  count     = var.alert_email == "" ? 0 : 1
  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

locals {
  alb_dimensions = {
    TargetGroup  = aws_lb_target_group.app.arn_suffix
    LoadBalancer = aws_lb.main.arn_suffix
  }
  rds_dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }
}

# --- Availability -----------------------------------------------------

# The "is the site down" alarm. Zero healthy targets means every
# request gets a 503 from the ALB. Missing data counts as breaching: no
# metric from the target group is itself a sign nothing is registered.
resource "aws_cloudwatch_metric_alarm" "no_healthy_hosts" {
  alarm_name          = "appointments-no-healthy-hosts"
  alarm_description   = "Site down: the ALB has no healthy targets to send traffic to"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HealthyHostCount"
  dimensions          = local.alb_dimensions
  statistic           = "Minimum"
  period              = 60
  evaluation_periods  = 2
  comparison_operator = "LessThanThreshold"
  threshold           = 1
  treat_missing_data  = "breaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Errors -----------------------------------------------------------

# 5xx generated by the ALB itself (no healthy target, target timeout,
# connection refused) — the visitor sees an AWS error page, not the app.
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name          = "appointments-alb-5xx"
  alarm_description   = "More than 5 ALB-generated 5xx responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  dimensions          = { LoadBalancer = aws_lb.main.arn_suffix }
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "GreaterThanThreshold"
  threshold           = 5
  treat_missing_data  = "notBreaching" # no 5xx emitted = no 5xx happened
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# 5xx returned by Django — the app is up but failing (DB auth, a bad
# migration, an unhandled exception).
resource "aws_cloudwatch_metric_alarm" "app_5xx" {
  alarm_name          = "appointments-app-5xx"
  alarm_description   = "More than 5 application 5xx responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  dimensions          = local.alb_dimensions
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "GreaterThanThreshold"
  threshold           = 5
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Latency ----------------------------------------------------------

# p95, not average: one slow DB query shouldn't hide behind fast static
# requests. 3 of 5 minutes so a single cold start doesn't page anyone.
resource "aws_cloudwatch_metric_alarm" "slow_responses" {
  alarm_name          = "appointments-slow-responses"
  alarm_description   = "p95 response time above 2s for 3 of the last 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "TargetResponseTime"
  dimensions          = local.alb_dimensions
  extended_statistic  = "p95"
  period              = 60
  evaluation_periods  = 5
  datapoints_to_alarm = 3
  comparison_operator = "GreaterThanThreshold"
  threshold           = 2
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Database ---------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "rds_cpu" {
  alarm_name          = "appointments-rds-cpu-high"
  alarm_description   = "RDS CPU above 80% for 10 minutes"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  dimensions          = local.rds_dimensions
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 2
  comparison_operator = "GreaterThanThreshold"
  threshold           = 80
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# 20 GB allocated (rds.tf); 2 GB left is time to grow it before MySQL
# stops accepting writes.
resource "aws_cloudwatch_metric_alarm" "rds_storage_low" {
  alarm_name          = "appointments-rds-storage-low"
  alarm_description   = "RDS free storage below 2 GB"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  dimensions          = local.rds_dimensions
  statistic           = "Minimum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "LessThanThreshold"
  threshold           = 2147483648 # 2 GiB in bytes
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Dashboard --------------------------------------------------------

resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = "appointments"

  dashboard_body = jsonencode({
    widgets = [
      {
        type = "metric", x = 0, y = 0, width = 12, height = 6
        properties = {
          title  = "Requests and errors"
          region = var.aws_region
          stat   = "Sum"
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", aws_lb.main.arn_suffix],
            [".", "HTTPCode_ELB_5XX_Count", ".", "."],
            [".", "HTTPCode_Target_5XX_Count", "TargetGroup", aws_lb_target_group.app.arn_suffix, "LoadBalancer", aws_lb.main.arn_suffix],
            [".", "HTTPCode_Target_4XX_Count", ".", ".", ".", "."],
          ]
        }
      },
      {
        type = "metric", x = 12, y = 0, width = 12, height = 6
        properties = {
          title  = "Response time (seconds)"
          region = var.aws_region
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "TargetResponseTime", "TargetGroup", aws_lb_target_group.app.arn_suffix, "LoadBalancer", aws_lb.main.arn_suffix, { stat = "p95", label = "p95" }],
            ["...", { stat = "p50", label = "p50" }],
          ]
        }
      },
      {
        type = "metric", x = 0, y = 6, width = 12, height = 6
        properties = {
          title  = "Target health"
          region = var.aws_region
          stat   = "Minimum"
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "HealthyHostCount", "TargetGroup", aws_lb_target_group.app.arn_suffix, "LoadBalancer", aws_lb.main.arn_suffix],
            [".", "UnHealthyHostCount", ".", ".", ".", ".", { stat = "Maximum" }],
          ]
        }
      },
      {
        type = "metric", x = 12, y = 6, width = 12, height = 6
        properties = {
          title  = "Database"
          region = var.aws_region
          period = 300
          metrics = [
            ["AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", aws_db_instance.main.identifier, { stat = "Average", label = "CPU %" }],
            [".", "DatabaseConnections", ".", ".", { stat = "Maximum", label = "Connections" }],
            [".", "FreeStorageSpace", ".", ".", { stat = "Minimum", label = "Free storage (bytes)", yAxis = "right" }],
          ]
        }
      },
    ]
  })
}
