# Alerting and a single-pane dashboard. Every alarm watches the ALB
# target group or the RDS instance, never the ASG: CodeDeploy replaces
# the ASG on every blue/green deploy (codedeploy.tf), so an alarm keyed
# on an ASG name would silently go stale after the first release. The
# target group and the DB instance are the two identities that survive
# every deploy.

# --- Notification channel ---------------------------------------------

# Customer-managed key, not alias/aws/sns: CloudWatch alarms can't
# publish to a topic encrypted with the AWS-managed SNS key, because
# that key's policy can't be edited to let cloudwatch.amazonaws.com use it.
resource "aws_kms_key" "alerts" {
  description             = "SNS alert topic encryption - appointments"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AccountAdmin"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" }
        Action    = "kms:*"
        Resource  = "*"
      },
      {
        Sid       = "CloudWatchAlarmsPublish"
        Effect    = "Allow"
        Principal = { Service = "cloudwatch.amazonaws.com" }
        Action    = ["kms:Decrypt", "kms:GenerateDataKey*"]
        Resource  = "*"
      },
    ]
  })
}

resource "aws_sns_topic" "alerts" {
  name              = "appointments-alerts"
  kms_master_key_id = aws_kms_key.alerts.id
}

# AWS emails a confirmation link to this address after apply; nothing
# is delivered until it's clicked.
resource "aws_sns_topic_subscription" "alerts_email" {
  count     = var.alert_email == "" ? 0 : 1
  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

locals {
  # Error budget = the share of requests allowed to fail (0.1% at 99.9%).
  # Burn-rate multipliers from the Google SRE workbook: 14.4x over 1h
  # spends 2% of a 30-day budget (page now); 6x over 6h spends 5%
  # (look today). Thresholds below are error-rate percentages.
  error_budget_pct    = 100 - var.slo_availability_target
  fast_burn_threshold = 14.4 * local.error_budget_pct
  slow_burn_threshold = 6 * local.error_budget_pct

  # Written by the CloudWatch agent (templates/user-data.sh.tpl).
  agent_metrics_namespace = "appointments/ContainerMetrics"

  alb_dimensions = {
    TargetGroup  = aws_lb_target_group.app.arn_suffix
    LoadBalancer = aws_lb.main.arn_suffix
  }
  rds_dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }
}

# --- Availability -----------------------------------------------------

# The "is the site down" alarm. Zero healthy targets means every
# request gets a 503 from the ALB. Missing data counts as breaching: no
# metric from the target group is itself a sign nothing is registered.
resource "aws_cloudwatch_metric_alarm" "no_healthy_hosts" {
  alarm_name          = "appointments-no-healthy-hosts"
  alarm_description   = "Site down: the ALB has no healthy targets to send traffic to"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HealthyHostCount"
  dimensions          = local.alb_dimensions
  statistic           = "Minimum"
  period              = 60
  evaluation_periods  = 2
  comparison_operator = "LessThanThreshold"
  threshold           = 1
  treat_missing_data  = "breaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Errors -----------------------------------------------------------

# 5xx generated by the ALB itself (no healthy target, target timeout,
# connection refused) — the visitor sees an AWS error page, not the app.
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name          = "appointments-alb-5xx"
  alarm_description   = "More than 5 ALB-generated 5xx responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  dimensions          = { LoadBalancer = aws_lb.main.arn_suffix }
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "GreaterThanThreshold"
  threshold           = 5
  treat_missing_data  = "notBreaching" # no 5xx emitted = no 5xx happened
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# 5xx returned by Django — the app is up but failing (DB auth, a bad
# migration, an unhandled exception).
resource "aws_cloudwatch_metric_alarm" "app_5xx" {
  alarm_name          = "appointments-app-5xx"
  alarm_description   = "More than 5 application 5xx responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  dimensions          = local.alb_dimensions
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "GreaterThanThreshold"
  threshold           = 5
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- SLOs (MONITORING.md) ---------------------------------------------

# Availability SLI = non-5xx requests / all requests at the ALB. The
# two burn-rate alarms fire while the SLO is *at risk*, long before the
# month's budget is gone. Low-traffic guard: under the minimum request
# count one stray 500 would read as a multi-percent error rate, so the
# expression reports 0 instead.
resource "aws_cloudwatch_metric_alarm" "slo_fast_burn" {
  alarm_name          = "appointments-slo-error-budget-fast-burn"
  alarm_description   = "Availability SLO at risk: 1h error rate is burning the ${var.slo_availability_target}% error budget at 14.4x (2% of the monthly budget gone in an hour)"
  comparison_operator = "GreaterThanThreshold"
  threshold           = local.fast_burn_threshold
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]

  metric_query {
    id          = "error_rate"
    label       = "5xx error rate (%) over 1h"
    expression  = "IF(requests >= 20, 100 * (FILL(elb_5xx, 0) + FILL(app_5xx, 0)) / requests, 0)"
    return_data = true
  }
  metric_query {
    id = "requests"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "RequestCount"
      dimensions  = { LoadBalancer = aws_lb.main.arn_suffix }
      period      = 3600
      stat        = "Sum"
    }
  }
  metric_query {
    id = "elb_5xx"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "HTTPCode_ELB_5XX_Count"
      dimensions  = { LoadBalancer = aws_lb.main.arn_suffix }
      period      = 3600
      stat        = "Sum"
    }
  }
  metric_query {
    id = "app_5xx"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "HTTPCode_Target_5XX_Count"
      dimensions  = local.alb_dimensions
      period      = 3600
      stat        = "Sum"
    }
  }
}

resource "aws_cloudwatch_metric_alarm" "slo_slow_burn" {
  alarm_name          = "appointments-slo-error-budget-slow-burn"
  alarm_description   = "Availability SLO at risk: 6h error rate is burning the ${var.slo_availability_target}% error budget at 6x (5% of the monthly budget gone in 6 hours)"
  comparison_operator = "GreaterThanThreshold"
  threshold           = local.slow_burn_threshold
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]

  metric_query {
    id          = "error_rate"
    label       = "5xx error rate (%) over 6h"
    expression  = "IF(requests >= 100, 100 * (FILL(elb_5xx, 0) + FILL(app_5xx, 0)) / requests, 0)"
    return_data = true
  }
  metric_query {
    id = "requests"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "RequestCount"
      dimensions  = { LoadBalancer = aws_lb.main.arn_suffix }
      period      = 21600
      stat        = "Sum"
    }
  }
  metric_query {
    id = "elb_5xx"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "HTTPCode_ELB_5XX_Count"
      dimensions  = { LoadBalancer = aws_lb.main.arn_suffix }
      period      = 21600
      stat        = "Sum"
    }
  }
  metric_query {
    id = "app_5xx"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "HTTPCode_Target_5XX_Count"
      dimensions  = local.alb_dimensions
      period      = 21600
      stat        = "Sum"
    }
  }
}

# Latency SLI = p95 TargetResponseTime. p95, not average: one slow DB
# query shouldn't hide behind fast static requests. 3 of 5 minutes so
# a single cold start doesn't page anyone.
resource "aws_cloudwatch_metric_alarm" "slo_latency" {
  alarm_name          = "appointments-slo-latency-p95"
  alarm_description   = "Latency SLO at risk: p95 response time above ${var.slo_latency_p95_seconds * 1000} ms for 3 of the last 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "TargetResponseTime"
  dimensions          = local.alb_dimensions
  extended_statistic  = "p95"
  period              = 60
  evaluation_periods  = 5
  datapoints_to_alarm = 3
  comparison_operator = "GreaterThanThreshold"
  threshold           = var.slo_latency_p95_seconds
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Database ---------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "rds_cpu" {
  alarm_name          = "appointments-rds-cpu-high"
  alarm_description   = "RDS CPU above 80% for 10 minutes"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  dimensions          = local.rds_dimensions
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 2
  comparison_operator = "GreaterThanThreshold"
  threshold           = 80
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# 20 GB allocated (rds.tf); 2 GB left is time to grow it before MySQL
# stops accepting writes.
resource "aws_cloudwatch_metric_alarm" "rds_storage_low" {
  alarm_name          = "appointments-rds-storage-low"
  alarm_description   = "RDS free storage below 2 GB"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  dimensions          = local.rds_dimensions
  statistic           = "Minimum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "LessThanThreshold"
  threshold           = 2147483648 # 2 GiB in bytes
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Instance resources (CloudWatch agent) ------------------------------

# Fleet roll-up series (no dimensions): Maximum = the busiest instance.
# Missing data is not breaching, so the alarms stay quiet until the
# first deploy after apply has instances running the new agent config.
resource "aws_cloudwatch_metric_alarm" "instance_memory_high" {
  alarm_name          = "appointments-instance-memory-high"
  alarm_description   = "An app instance is above 85% memory for 10 minutes (t4g.small has 2 GiB)"
  namespace           = local.agent_metrics_namespace
  metric_name         = "mem_used_percent"
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 2
  comparison_operator = "GreaterThanThreshold"
  threshold           = 85
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

resource "aws_cloudwatch_metric_alarm" "instance_disk_high" {
  alarm_name          = "appointments-instance-disk-high"
  alarm_description   = "An app instance root volume is above 80% full (Docker images accumulate on the 20 GB volume)"
  namespace           = local.agent_metrics_namespace
  metric_name         = "disk_used_percent"
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 1
  comparison_operator = "GreaterThanThreshold"
  threshold           = 80
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

resource "aws_cloudwatch_metric_alarm" "instance_cpu_high" {
  alarm_name          = "appointments-instance-cpu-high"
  alarm_description   = "An app instance is above 80% CPU for 10 minutes"
  namespace           = local.agent_metrics_namespace
  metric_name         = "cpu_usage_active"
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 2
  comparison_operator = "GreaterThanThreshold"
  threshold           = 80
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
}

# --- Dashboard --------------------------------------------------------

# One dashboard, read top-down by audience: the status row answers "is
# the service OK and within SLO?" for anyone; the rows below are the
# on-call view (traffic, latency, errors, capacity, database).
resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = "appointments"

  dashboard_body = jsonencode({
    widgets = [
      {
        type = "text", x = 0, y = 0, width = 8, height = 6
        properties = {
          markdown = join("\n", [
            "## Appointments: service status",
            "**Availability SLO:** ${var.slo_availability_target}% of requests succeed (30 days)",
            "",
            "**Latency SLO:** p95 under ${var.slo_latency_p95_seconds * 1000} ms",
            "",
            "Alarms email the SNS topic `${aws_sns_topic.alerts.name}`.",
            "Runbook: MONITORING.md in the repo.",
          ])
        }
      },
      {
        type = "alarm", x = 8, y = 0, width = 16, height = 6
        properties = {
          title = "Alarm status"
          alarms = [
            aws_cloudwatch_metric_alarm.no_healthy_hosts.arn,
            aws_cloudwatch_metric_alarm.slo_fast_burn.arn,
            aws_cloudwatch_metric_alarm.slo_slow_burn.arn,
            aws_cloudwatch_metric_alarm.slo_latency.arn,
            aws_cloudwatch_metric_alarm.alb_5xx.arn,
            aws_cloudwatch_metric_alarm.app_5xx.arn,
            aws_cloudwatch_metric_alarm.unhealthy_hosts.arn,
            aws_cloudwatch_metric_alarm.rds_cpu.arn,
            aws_cloudwatch_metric_alarm.rds_storage_low.arn,
            aws_cloudwatch_metric_alarm.instance_memory_high.arn,
            aws_cloudwatch_metric_alarm.instance_disk_high.arn,
            aws_cloudwatch_metric_alarm.instance_cpu_high.arn,
          ]
        }
      },
      {
        type = "metric", x = 0, y = 6, width = 8, height = 6
        properties = {
          title  = "Requests per second"
          region = var.aws_region
          period = 60
          stat   = "Sum"
          metrics = [
            [{ expression = "requests / PERIOD(requests)", label = "Requests/sec", id = "rps" }],
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", aws_lb.main.arn_suffix, { id = "requests", visible = false }],
          ]
        }
      },
      {
        type = "metric", x = 8, y = 6, width = 8, height = 6
        properties = {
          title  = "Latency p95 vs SLO (seconds)"
          region = var.aws_region
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "TargetResponseTime", "TargetGroup", aws_lb_target_group.app.arn_suffix, "LoadBalancer", aws_lb.main.arn_suffix, { stat = "p95", label = "p95" }],
            ["...", { stat = "p50", label = "p50" }],
          ]
          annotations = {
            horizontal = [{ label = "SLO", value = var.slo_latency_p95_seconds }]
          }
        }
      },
      {
        type = "metric", x = 16, y = 6, width = 8, height = 6
        properties = {
          title  = "Error rate vs SLO (% of requests)"
          region = var.aws_region
          period = 300
          stat   = "Sum"
          metrics = [
            [{ expression = "100 * (FILL(elb_5xx, 0) + FILL(app_5xx, 0)) / requests", label = "5xx error rate %", id = "error_rate" }],
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", aws_lb.main.arn_suffix, { id = "requests", visible = false }],
            [".", "HTTPCode_ELB_5XX_Count", ".", ".", { id = "elb_5xx", visible = false }],
            [".", "HTTPCode_Target_5XX_Count", "TargetGroup", aws_lb_target_group.app.arn_suffix, "LoadBalancer", aws_lb.main.arn_suffix, { id = "app_5xx", visible = false }],
          ]
          annotations = {
            horizontal = [{ label = "Error budget", value = local.error_budget_pct }]
          }
        }
      },
      {
        type = "metric", x = 0, y = 12, width = 12, height = 6
        properties = {
          title  = "Target health"
          region = var.aws_region
          stat   = "Minimum"
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "HealthyHostCount", "TargetGroup", aws_lb_target_group.app.arn_suffix, "LoadBalancer", aws_lb.main.arn_suffix],
            [".", "UnHealthyHostCount", ".", ".", ".", ".", { stat = "Maximum" }],
          ]
        }
      },
      {
        type = "metric", x = 12, y = 12, width = 12, height = 6
        properties = {
          title  = "Database"
          region = var.aws_region
          period = 300
          metrics = [
            ["AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", aws_db_instance.main.identifier, { stat = "Average", label = "CPU %" }],
            [".", "DatabaseConnections", ".", ".", { stat = "Maximum", label = "Connections" }],
            [".", "FreeStorageSpace", ".", ".", { stat = "Minimum", label = "Free storage (bytes)", yAxis = "right" }],
          ]
        }
      },
      {
        type = "metric", x = 0, y = 18, width = 8, height = 6
        properties = {
          title  = "Instance memory used % (per instance)"
          region = var.aws_region
          period = 60
          yAxis  = { left = { min = 0, max = 100 } }
          metrics = [
            [{ expression = "SEARCH('{${local.agent_metrics_namespace},InstanceId} MetricName=\"mem_used_percent\"', 'Average', 60)", id = "mem" }],
          ]
          annotations = { horizontal = [{ label = "Alarm", value = 85 }] }
        }
      },
      {
        type = "metric", x = 8, y = 18, width = 8, height = 6
        properties = {
          title  = "Instance disk used % (root volume)"
          region = var.aws_region
          period = 300
          yAxis  = { left = { min = 0, max = 100 } }
          metrics = [
            [{ expression = "SEARCH('{${local.agent_metrics_namespace},InstanceId,path,fstype} MetricName=\"disk_used_percent\"', 'Maximum', 300)", id = "disk" }],
          ]
          annotations = { horizontal = [{ label = "Alarm", value = 80 }] }
        }
      },
      {
        type = "metric", x = 16, y = 18, width = 8, height = 6
        properties = {
          title  = "Instance CPU %"
          region = var.aws_region
          period = 60
          yAxis  = { left = { min = 0, max = 100 } }
          metrics = [
            [{ expression = "SEARCH('{${local.agent_metrics_namespace},InstanceId,cpu} MetricName=\"cpu_usage_active\"', 'Average', 60)", id = "cpu" }],
          ]
          annotations = { horizontal = [{ label = "Alarm", value = 80 }] }
        }
      },
    ]
  })
}

# --- Saved Logs Insights queries ---------------------------------------

# The first two places to look when an alarm fires; saved so nobody has
# to remember the syntax mid-incident.
resource "aws_cloudwatch_query_definition" "app_errors" {
  name            = "appointments/app-errors"
  log_group_names = [aws_cloudwatch_log_group.app.name]
  query_string    = <<-EOT
    fields @timestamp, @message
    | filter @message like /(?i)(error|exception|traceback)/
    | sort @timestamp desc
    | limit 50
  EOT
}

resource "aws_cloudwatch_query_definition" "vpc_rejects" {
  name            = "appointments/vpc-rejected-traffic"
  log_group_names = [aws_cloudwatch_log_group.vpc_flow_logs.name]
  query_string    = <<-EOT
    fields srcAddr, dstPort
    | filter action = "REJECT"
    | stats count(*) as attempts by srcAddr, dstPort
    | sort attempts desc
    | limit 20
  EOT
}

# Django's runserver logs one line per request to the app log group:
#   [03/Oct/2026 08:22:11] "GET /wp-login.php HTTP/1.1" 404 2543
# This groups the 4xx by status and path: bots probing for WordPress or
# .env files show up as many paths with 404; a broken link or form
# shows up as one real path repeating.
resource "aws_cloudwatch_query_definition" "http_4xx" {
  name            = "appointments/http-4xx-by-path"
  log_group_names = [aws_cloudwatch_log_group.app.name]
  query_string    = <<-EOT
    fields @timestamp, @message
    | parse @message /"(?<method>[A-Z]+) (?<path>\S+) [^"]*" (?<status>\d{3})/
    | filter status like /^4/
    | stats count(*) as hits by status, method, path
    | sort hits desc
    | limit 25
  EOT
}
